### ISSUE TITLE
What GPUs are your experiments running on, and how many are needed?

### ISSUE THREAD

**Issue by negan7879** [Koorye/DePT#2]

**Comment by Koorye** [comment]
Thank you for your interest in our work. We run our experminents on a single V100 GPU.

**Comment by negan7879** [comment]
> Thank you for your interest in our work. We run our experminents on a single V100 GPU.

Thanks for the reply, how long does it take to execute on a single A100？

**Comment by negan7879** [comment]
> Thank you for your interest in our work. We run our experminents on a single V100 GPU.

Thanks for the reply, how long does it take to execute on a single V100?

**Comment by Koorye** [comment]
> > Thank you for your interest in our work. We run our experminents on a single V100 GPU.
> 
> Thanks for the reply, how long does it take to execute on a single V100?

For the base-to-new generalization task, our method takes approximately 4 hours to run on all datasets with a random seed. For cross-dataset transfer tasks, this would take approximately 8 hours.

The above results are based on the CoOp method, with varying training times for each method. Our method does not increase additional training time.
