### ISSUE TITLE
 supplementary material

### ISSUE THREAD

**Issue by weiyingxue** [Koorye/DePT#3]
Could you publish the supplementary material please?
Thanks in advance,
Best regardsBest regards

**Comment by JimZAI** [comment]
Hi, Thanks for your interest in our DePT.

The Sup. Mat. of DePT and the code of PromptSRC+DePT are publicly available at [Here](https://pan.baidu.com/s/18E6M60LCbAvQcLloI4l3Qg );  code: dept

Note that the two baseline methods VPT and PromptSRC were added to the paper after the rebuttal phase (suggested by Reviewers)，so we did not report the domain generalization results of the two methods in this vision of Sup. Mat. However, we believe you can easily reproduce the results following our Github repo.   

Best,

Ji Zhang

**Comment by JimZAI** [comment]
> Could you publish the supplementary material please? Thanks in advance, Best regardsBest regards

Hi, Thanks for your interest in our DePT.

The Sup. Mat. of DePT and the code of PromptSRC+DePT are publicly available at [Here](https://pan.baidu.com/s/18E6M60LCbAvQcLloI4l3Qg );  password: **dept**

Note that the two baseline methods VPT and PromptSRC were added to the paper after the rebuttal phase (suggested by Reviewers)，so we did not report the domain generalization results of the two methods in this vision of Sup. Mat. However, we believe you can easily reproduce the results following our Github repo.   

Best,

Ji Zhang
