### ISSUE TITLE
Request for PromptSrc code

### ISSUE THREAD

**Issue by srinu274** [Koorye/DePT#4]
Hi,

If and when are you planning to release code for Promptsrc?

Thanks

**Comment by JimZAI** [comment]
> Hi,
> 
> If and when are you planning to release code for Promptsrc?
> 
> Thanks

Hi, Thanks for your interest in our DePT.

The Sup. Mat. of DePT and the code of PromptSRC+DePT are publicly available at [Here](https://pan.baidu.com/s/18E6M60LCbAvQcLloI4l3Qg );  password : **dept**

Note that the two baseline methods VPT and PromptSRC were added to the paper after the rebuttal phase (suggested by Reviewers)，so we did not report the domain generalization results of the two methods in this vision of Sup. Mat. However, we believe you can easily reproduce the results following our Github repo.   

Best,

Ji Zhang

**Comment by srinu274** [comment]
Hello, 

Thanks for sharing the code. It is password protected and it is not openly accessible.

**Comment by JimZAI** [comment]
The password is **dept**.
