### ISSUE TITLE
Domain Generalization Results

### ISSUE THREAD

**Issue by 1215481871** [Koorye/DePT#6]
Thanks for your excellent work!

Can you please provide the domain generlization results on imagenet-a, sktech, etc.

As you said in the main text, there are supposed to be appeared in Supplementary.D. But I still can't find the results.

Best regards,

**Comment by Koorye** [comment]
Thanks for your interest in our work, we present the domain generalization results in `additional_results/domain_generalization.md`.

**Comment by 1215481871** [comment]
Thanks for your reply!
