### ISSUE TITLE
visual code analysis about Figure 3

### ISSUE THREAD

**Issue by Harzva** [Koorye/DePT#7]
This is a great job, and the relevant analysis is also very comprehensive. 
Can you provide a visual code analysis for Figure 3? This will help me understand,thank you！

**Comment by Koorye** [comment]
Thank you for your interest in our work. The visual code is located in `tests/channel_importance.py`. If you need to use this code, you will need to:
1. Save the image/text features of a method as `pkl`, for example, you can use the `test/save_stats.py` script to run the `OracleStats` method to get the result.
2. Run `channel_importance.py` for visualization.
